name: PHP Linting (Pint)

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@1.0.0
        with:
          preset: laravel
