# This workflow is temporary, trying to get GitHub Actions working in this repository.

name: Temporary

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: date
